# Generated by Django 4.1.6 on 2023-09-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BqResults",
            fields=[
                (
                    "store_id",
                    models.CharField(max_length=19, primary_key=True, serialize=False),
                ),
                (
                    "timezone_str",
                    models.CharField(blank=True, max_length=28, null=True),
                ),
            ],
            options={
                "db_table": "bq_results",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MenuHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.CharField(blank=True, max_length=19, null=True)),
                ("day", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "start_time_local",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "end_time_local",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
            ],
            options={
                "db_table": "menu_hours",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "report_id",
                    models.CharField(max_length=90, primary_key=True, serialize=False),
                ),
                ("status", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "reports",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StoreStatus",
            fields=[
                ("store_id", models.CharField(blank=True, max_length=19, null=True)),
                ("status", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "timestamp_utc",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "id",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "store_status",
                "managed": True,
            },
        ),
    ]
